name: tests

on:
  workflow_dispatch: { }
  push:
    branches: [ default ]
    paths: [ "src/**", "test/**", "project.clj" ]
  pull_request:
    paths: [ "src/**", "test/**", "project.clj" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - run: lein test

      - run: lein cljs-test
